#########################
# Example docker compose to build olvid/map-server from source and for development
#########################
services:
  map:
    image: olvid/map-server
    build: ./docker
    environment:
      - SERVER_PUBLIC_URL=http://localhost:8080
      - STYLES_OSM=colorful,graybeard,eclipse,neutrino,shadow
      - ENABLE_LOCALIZATION=true
      - DATA_FILES=/data/osm.versatiles
    volumes:
      - ./data:/data:ro
    ports:
      - "8080:8080"
